apiVersion: v1
kind: Service
metadata:
  name: ray-head-svc-expose
  namespace: ray
spec:
  type: NodePort           # Exposes the service on all nodes
  selector:
    ray.io/identifier: raycluster-kuberay-head
    ray.io/node-type: head
  ports:
    - protocol: TCP
      port: 8265           # The port exposed by the service
      targetPort: 8265       # The container/pod port to route traffic to
      nodePort: 30000      # Fixed NodePort (optional)
